apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-krj1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-krj1@sha256:7102cb56bba0eb52ffd4858999cd51c37f61c52307a7bbe3dfa11f5098af03ee
        name: my-nodejs
        resources: {}
status: {}
